/**
 * ---===[Autogenerated file]===---
 * If you want to make changes, edit the root .eslintrc.json file and then run the command "npm run copy"
 */
module.exports = {
    env: {
        node: true,
        commonjs: false,
        es6: true,
        mocha: true,
    },
    settings: {
        jsdoc: {mode: 'typescript'},
    },
    extends: [
        'eslint:recommended',
        'google',
        'prettier',
        'plugin:jsdoc/recommended',
        'plugin:node/recommended',
        'plugin:import/errors',
        'plugin:import/warnings',
        'plugin:sonarjs/recommended',
        'plugin:promise/recommended',
        'plugin:security/recommended',
    ],
    plugins: ['jsdoc', 'prettier', 'node', 'sonarjs', 'promise', 'security'],
    globals: {},
    parserOptions: {
        ecmaVersion: 2021,
        sourceType: 'module',
    },
    overrides: [
        {
            files: ['test/*'],
            rules: {
                'no-unused-vars': 'off',
                'node/no-unpublished-require': 'off',
                'node/no-unpublished-import': 'off',
                'jsdoc/require-jsdoc': 'off',
            },
        },
    ],
    rules: {
        indent: ['off'],
        'max-len': ['off'],
        'require-jsdoc': ['off'],
        'valid-jsdoc': 'off',
        'promise/always-return': 'off',
    },
};
