name: "Build"

on:
  push:
    branches-ignore: [main]
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      # Skip post-install scripts here, as a malicious
      # script could steal NODE_AUTH_TOKEN.
      - name: Install Dependencies
        run: |
          npm install --ignore-scripts
      - name: Run linting
        run: npm run lint
      - name: Run tests
        run: npm run test-ci
