name: "NPM Publish"

on:
  push:
    branches:
      - main
      
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/
      - name: Install Dependencies
        run: |
          npm install --ignore-scripts
      - name: Audit packages
        run: npm audit --audit-level=high --omit=dev
      - name: Run linting
        run: npm run lint
      - name: Run tests
        run: npm run test-ci

  deploy:
    needs: [build]
    environment: npm-publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/
      - run: |
          npm publish --access public
